### Whether the first-person narrative perspective improves readers' memory more effectively than the third-person narrative perspective?

In [7]:
# Construct Contingency Matrix for mental imagery 
import numpy as np
import pandas as pd


# Hypothesis 1: The First-person perspective is more likely to trigger mental imagery than the third-person perspective
nar_data=pd.read_csv('narrative perspective.csv', encoding='gbk')
first_nar=nar_data[nar_data['Narrative_Perspective']=='F']
first_nar_men=[item for item in first_nar['Mental_Imagery'] if item=='Y']
first_nar_no_men=[item for item in first_nar['Mental_Imagery'] if item=='N']

third_nar=nar_data[nar_data['Narrative_Perspective']=='T']
third_nar_men=[item for item in third_nar['Mental_Imagery'] if item=='Y']
third_nar_no_men=[item for item in third_nar['Mental_Imagery'] if item=='N']


# We can store the observed frequencies in a list
data4contingency = []
data4contingency.append(len(first_nar_men))
data4contingency.append(len(third_nar_men))
data4contingency.append(len(first_nar_no_men))
data4contingency.append(len(third_nar_no_men))

print('The values:')
print(data4contingency)

# We transform the list in a contingency matrix
data_cm = np.array(data4contingency).reshape(2,-1)

print('The contingency matrix')
print(data_cm)

The values:
[3, 3, 13, 11]
The contingency matrix
[[ 3  3]
 [13 11]]


In [8]:
# Perform the Chi-square test
from scipy.stats import chi2_contingency 
chi2, p_value, degree_of_freedom, expected_frequencies = chi2_contingency(data_cm)
print(chi2, p_value)
print('These are the expected frequencies')
print(expected_frequencies)

if p_value < 0.05:
    print("The observed differences are statiscally significant - H0 is rejected")
else:
    print("The observed differences are not statiscally significant - H1 is rejected")

0.0 1.0
These are the expected frequencies
[[ 3.2  2.8]
 [12.8 11.2]]
The observed differences are not statiscally significant - H1 is rejected


### Whether the first-person narrative perspective leads to more memories containing mental imagery compared to the third-person narrative perspective?

In [9]:
# Construct Contingency Matrix for emotional engagement
import numpy as np
import pandas as pd


# Hypothesis 1: The First-person perspective is more likely to trigger emotions than the third-person perspective
nar_data=pd.read_csv('C:/Users/14359/Desktop/narrative perspective.csv', encoding='gbk')
first_nar=nar_data[nar_data['Narrative_Perspective']=='F']
first_nar_emo=[item for item in first_nar['Emotional_Engagement'] if item=='Y']
first_nar_no_emo=[item for item in first_nar['Emotional_Engagement'] if item=='N']

third_nar=nar_data[nar_data['Narrative_Perspective']=='T']
third_nar_emo=[item for item in third_nar['Emotional_Engagement'] if item=='Y']
third_nar_no_emo=[item for item in third_nar['Emotional_Engagement'] if item=='N']


# We can store the observed frequencies in a list
data4contingency = []
data4contingency.append(len(first_nar_emo))
data4contingency.append(len(third_nar_emo))
data4contingency.append(len(first_nar_no_emo))
data4contingency.append(len(third_nar_no_emo))

print('The values:')
print(data4contingency)

# We transform the list in a contingency matrix
data_cm = np.array(data4contingency).reshape(2,-1)

print('The contingency matrix')
print(data_cm)

The values:
[11, 10, 5, 4]
The contingency matrix
[[11 10]
 [ 5  4]]


In [10]:
# Perform the Chi-square test
from scipy.stats import chi2_contingency 
chi2, p_value, degree_of_freedom, expected_frequencies = chi2_contingency(data_cm)
print(chi2, p_value)
print('These are the expected frequencies')
print(expected_frequencies)

if p_value < 0.05:
    print("The observed differences are statiscally significant - H0 is rejected")
else:
    print("The observed differences are not statiscally significant - H1 is rejected")

0.0 1.0
These are the expected frequencies
[[11.2  9.8]
 [ 4.8  4.2]]
The observed differences are not statiscally significant - H1 is rejected


### Whether the first-person narrative perspective triggers emotional memories compared to the third-person narrative perspective?

In [11]:
# Construct Contingency Matrix for recollections of contents
import numpy as np
import pandas as pd


# Hypothesis 1: The First-person perspective is more likely to make readers remember contents than the third-person perspective
nar_data=pd.read_csv('C:/Users/14359/Desktop/narrative perspective.csv', encoding='gbk')
first_nar=nar_data[nar_data['Narrative_Perspective']=='F']
first_nar_con=[item for item in first_nar['REC_CONTENT'] if item=='Y']
first_nar_no_con=[item for item in first_nar['REC_CONTENT'] if item=='N']

third_nar=nar_data[nar_data['Narrative_Perspective']=='T']
third_nar_con=[item for item in third_nar['REC_CONTENT'] if item=='Y']
third_nar_no_con=[item for item in third_nar['REC_CONTENT'] if item=='N']


# We can store the observed frequencies in a list
data4contingency = []
data4contingency.append(len(first_nar_con))
data4contingency.append(len(third_nar_con))
data4contingency.append(len(first_nar_no_con))
data4contingency.append(len(third_nar_no_con))

print('The values:')
print(data4contingency)

# We transform the list in a contingency matrix
data_cm = np.array(data4contingency).reshape(2,-1)

print('The contingency matrix')
print(data_cm)

The values:
[12, 10, 4, 4]
The contingency matrix
[[12 10]
 [ 4  4]]


In [12]:
# Perform the Chi-square test
from scipy.stats import chi2_contingency 
chi2, p_value, degree_of_freedom, expected_frequencies = chi2_contingency(data_cm)
print(chi2, p_value)
print('These are the expected frequencies')
print(expected_frequencies)

if p_value < 0.05:
    print("The observed differences are statiscally significant - H0 is rejected")
else:
    print("The observed differences are not statiscally significant - H1 is rejected")

0.0 1.0
These are the expected frequencies
[[11.73333333 10.26666667]
 [ 4.26666667  3.73333333]]
The observed differences are not statiscally significant - H1 is rejected
